### PR TITLE
Store deserialized dev

### PR DESCRIPTION
**Pull request by leplatrem**
Same as #70, rebased.

### CODE REVIEW

**Comment by almet** [comment]
I suggest we MERGE master, and not rebase it for this.

**Comment by leplatrem** [comment]
As you want, but just be aware that it was not a piece of cake to rebase/merge this :)

**Comment by almet** [comment]
The rationale behind this is that otherwise, we'll get two different branches that are not related to each other. And thus have a divergent history, which makes usually things complicated.

Let's try to avoid that.

**Comment by almet** [comment]
See #80

**Pull request closed without merging**
