### PR TITLE
GeoJSON renderer

### LINKED ISSUE #12: Records formatting
`Accept` HTTP directive may not be enough to format records.

For example, getting the records of a model which contain a geometry as JSON may have two formattings :
- a basic JSON (as currently : `[ {...}, {...} ]`)
- a GeoJSON ( `{ "type": "FeatureCollection", "features": [{...}, {...}]`), that integrates nicely in JS map widgets like Leaflet.

Both are valid JSON. We might need a `?format=XXX` parameter to specify which layout it should have.

### PR DESCRIPTION
**Pull request by leplatrem**
(fixes #12)

### CODE REVIEW

**Comment by leplatrem** [comment]
Looks like `Accept` with profile is being ignored at the moment :)

**Comment by almet** [comment]
in Cornice or in pyramid?

**Comment by leplatrem** [comment]
No clue yet... just from the functional tests point of view :)

**Comment by leplatrem** [comment]
Closing, a new PR into dev branch was created #68

**Pull request closed without merging**
