### PR TITLE
Get rid of separate views modules for collections

### PR DESCRIPTION
**Pull request by Natim**
Merge definition.py in models.py and data_items.py in data.py.

Refs #95

### CODE REVIEW

**Comment by leplatrem** [comment]
Good game @Natim !

Congratz :) Daybed will rock !

**Comment by Natim** [comment]
Of course Daybed rocks :)

**Comment by Natim** [comment]
Btw I miss you on irc.freenode.net/#daybed

**Comment by leplatrem** [comment]
Sorry j'suis chez mes beaux-parents ! Je suis pas vraiment posé :)

**Pull request merged**
