### PR TITLE
Add relations fields

### PR DESCRIPTION
**Pull request by leplatrem**
Most of the work here consisted in giving a reference to database from validators to field types checking. 
The rest is quite obvious.
# Behaviour

Can only reference an `id` of the linked model. Posting a record of the linked model directly is not supported.
# Code

Could not find any way to take a shortcut ! (app registry ? events ?)
# Storage

Wonder if we should serialize into somewhere more HATEOAS : 

Instead of : 

`abcdefgh`

store (and serve) this : 

```
{id: 'abcdefgh',
 model: 'simple',
 uri: '/models/simple/data/abcdefgh'}
```

Please comment :)

### CODE REVIEW

**Comment by almet** [comment]
I agree, this solution is kinda weird because we're passing the request to the SchemaValidator which in turn pass it to the other who needs it, but we only want to access the db instance.

I can see different ways to solve this:
- pass the db directly
- make the db a global object we can access from anywhere. In practice this is a bad idea but in theory having it implemented as a singleton can make things easier to manage and can stay thread-safe, and improve the readability of the code
- stay as you did it, in case we will want to have schema matching on other stuff that what we already checked in the request.

My personal perference goes to 2. since it means we need to touch less code, but I'm feeling that's kinda of hackish.

**Comment by leplatrem** [comment]
I also prefer 2 !

I thought there was a way to obtain a global `application` instance, from there access `config`, then `registry`, then `db`...
But I didn't find any way that day...

**Comment by almet** [comment]
Oh, good call. We actually can use `get_current_registry()`! http://docs.pylonsproject.org/projects/pyramid/en/1.0-branch/api/threadlocal.html#pyramid.threadlocal.get_current_registry

**Comment by leplatrem** [comment]
Recommended to avoid usage outside tests:
http://docs.pylonsproject.org/projects/pyramid/en/1.0-branch/api/threadlocal.html#pyramid.threadlocal.get_current_registry

Singletons do not match pyramid design:
http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/introduction.html#no-singletons 

I thought I could make config object a daybed module attribute...
http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/introduction.html#automating-repetitive-configuration

But preferred the `global_registries` attribute of pyramid config module !
http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html

**Comment by leplatrem** [comment]
@AntoineCezar was not very enthusiast about this `from pyramid.config import global_registries` 

That's the only way to validate using decorators, and I like its brevity. Plus, it does not break any pyramid pattern AFAIK. 

Otherwise something similar to this has to be implemented: https://github.com/spiral-project/daybed/blob/5ba78/daybed/views/data_item.py#L52-L54

@ametaireau any objection ?

**Comment by almet** [comment]
I don't have strong feelings either way: we should be careful about our use of the global registries, but I think this is a good usecase for it.

**Comment by leplatrem** [comment]
done !

**Pull request merged**
