### PR TITLE
Add a Redis storage

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by Natim** [comment]
When refactor-acls will be merge I will be able to rebase on master.

**Comment by almet** [comment]
you can rebase ;)

**Comment by Natim** [comment]
Done

**Comment by almet** [comment]
boom

**Comment by leplatrem** [comment]
Coverage going doooown :) 

```
Name                            Stmts   Miss  Cover   Missing
-------------------------------------------------------------
daybed.backends.couchdb           121      8    93%   25-28, 56, 98, 140, 166-167
daybed.backends.redis              97      4    96%   13-15, 81
daybed.renderers                   51      1    98%   3
daybed.schemas.list                35      2    94%   11-12
daybed.tokens                      45      6    87%   14, 26-27, 45, 47, 54
daybed.views.models                55      1    98%   79
daybed.views.records               79      2    97%   55, 114
-------------------------------------------------------------
TOTAL                            1328     24    98%   
----------------------------------------------------------------------
Ran 191 tests in 15.064s

OK
```

**Comment by almet** [comment]
heh. We'll get it back to 100% soon :)

**Pull request merged**
